apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: deployer
rules:
- apiGroups: [""] 
  resources: ["services", "pods"]
  verbs: ["get", "update", "patch", "create", "list"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "update", "patch", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: production
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: production 